### ISSUE TITLE
Leaks file descriptors when using paging.

### ISSUE THREAD

**Issue by joharohl** [sparkfun/phant-stream-json#1]
File descriptors are leaking when paging is used. This is due to attaching to the [wrong event in the initializer](https://github.com/sparkfun/phant-stream-json/blob/master/lib/readable.js#L58).  Changing the event from `finalize` to `end` fixes the bug but creates a new one when paging is not used since the last opened file will be closed twice, throwing an exception. This can be fixed in many ways I guess but I found the nicest to be to move the closing of the file in nextPage to reside inside the check for if the file exists. This way, there is always a file to be closed when the end event is triggered.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
